#!/bin/bash

rowsum() # default
{
awk '{sum=0; for (i=1; i<=NF; i++) { sum+= $i } print $0,sum}'
}

rowsum_only() # -n
{
awk '{sum=0; for (i=1; i<=NF; i++) { sum+= $i } print sum}'
}

rowsum_count() # -c
{
awk '{sum=0; {for (i=1; i<=NF; i++) { if($i>0 && $i~/^[0-9]*$/) sum+= 1; }} print sum}'
}

usage() # -h
{
cat <<HELP 
usage: rowsums [OPTION...] 
	-h, 		This help page
	-n,		Print only the rowsums and not the original row + rowsum
	-c,		Print the rowsum as the total number of elements that have a value > 0 rather than the sum of those values 
	 		Default with no option prints the row then the sum at the end
HELP 

exit
}

### Main

#defaults here

while getopts 'h|n|c' option
do
	case ${option} in
		h) usage ;;
		n) rowsum_only;exit ;;
		c) rowsum_count; exit ;;
	esac
done

rowsum


